source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FLCommonLibraryPod_Example', :exclusive => true do
  pod "FLCommonLibraryPod", :path => "../"
end

target 'FLCommonLibraryPod_Tests', :exclusive => true do
  pod "FLCommonLibraryPod", :path => "../"

  pod 'FBSnapshotTestCase'
end
